AWSTemplateFormatVersion: '2010-09-09'

Description: EC2 t3.micro with SSH and HTTP access

Parameters:

  MyIP:
    Type: String
    Description: Your public IP address in CIDR notation

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair name

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from my IP and HTTP from anywhere

      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: EC2-SecurityGroup

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b245cc5f82576748
      InstanceType: t3.micro
      KeyName: !Ref KeyName

      SecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId

      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: 8
            DeleteOnTermination: true

      Tags:
        - Key: Name
          Value: MyCloudFormationEC2
