AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue basico de una instancia EC2

Resources:
  MiInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c7217cdde317cfec
      Tags:
        - Key: Name
          Value: MiInstanciaEC2
