AWSTemplateFormatVersion: '2010-09-09'

Resources:

  MiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir SSH solo desde mi IP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 200.10.20.30/32

  MiInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e34b50e714a297f1
      InstanceType: t3.micro
      SubnetId: subnet-0e76324a978f7922b
      SecurityGroupIds:
        - sg-07123c0fc2b8a336a
      IamInstanceProfile: rol-ec2-devops
      Tags:
        - Key: Name
          Value: mi-web-publica

  MiBaseDeDatosRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: mibase-postgres
      Engine: postgres
      EngineVersion: "15.19"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: postgresuser
      MasterUserPassword: PasswordSeguro123!
      PubliclyAccessible: false
